comexio/php-utils

tests/Exceptions/ApiExceptionUnitTest.php, tests/Exceptions/BadImplementationExceptionUnitTest.php, tests/Exceptions/SecurityExceptionUnitTest.php, tests/Handlers/ExceptionHandlerUnitTest.php, tests/Middlewares/AccreditedApiKeysMiddlewareUnitTest.php
Ajuste dos testes de Exceptions, para testar o conteudo principal, e atualizado o Namespace do AccreditedApiKeysMiddleware
=> Ajuste dos Testes que estavam falhando

README.md, src/Handlers/ExceptionHandler.php, src/Helpers/EnumHelper.php, tests/Helpers/EnumHelperUnitTest.php
- Externalizado EnumHelper
- Criado testes para ele
- Refeita documentação
=> EnumHelper

src/Handlers/ExceptionHandler.php
=> Changing the error patter log, to follow the same of the request info

src/Handlers/ExceptionHandler.php, tests/Handlers/ExceptionHandlerUnitTest.php
=> Changing exportExceptionToArray to static, to be used of a easy way

src/Contracts/BuilderContract.php
=> Created BuilderContract

src/Contracts/BuilderContract.php
=> Corrigido BuilderContract

composer.json, src/Contracts/BuilderContract.php
Fixing PSR-4 composer namespace
=> Fixing PSR-4 composer namespace

.gitignore, .travis.yml, composer.lock, src/Functionalities/PropertiesAttacherFunctionality.php, tests/Functionalities/PropertiesAttacherFunctionalityUnitTest.php
- Corrigido maneira como é anexado os valores no PropertiesAttacherFunctionality.
- Criado teste unitário que cobre o problema.
=> PropertiesAttacherFunctionality

README.md, src/Middlewares/AuthenticateMiddleware.php, tests/Middlewares/AuthenticateMiddlewareUnitTest.php
- Created AuthenticateMiddleware.php
- Created AuthenticateMiddlewareUnitTest.php
- Documented AuthenticateMiddleware
=> Feature - AuthenticateMiddleware

README.md, src/Exceptions/BadImplementationException.php, src/Exceptions/UnavailableServiceException.php, src/Functionalities/PropertiesAttacherFunctionality.php, src/Functionalities/ValuesExporterToArrayFunctionality.php, src/Handlers/ExceptionHandler.php, src/Helpers/HttpHelper.php, tests/Exceptions/BadImplementationExceptionUnitTest.php, tests/Exceptions/UnavailableServiceExceptionUnitTest.php, tests/Handlers/ExceptionHandlerUnitTest.php, tests/Helpers/HttpHelperUnitTest.php
- Criada nova exceção para lidar com serviço fora do ar.
- Adicionada a mesma no ExceptionHandler.php
- Alterada documentação
- Alterada exceção BadImplementationException.php para pedir token também.
=> New UnavailableServiceException

README.md, bootstrap/start.php, src/Helpers/HttpHelper.php, src/Logs/RequestInfoLog.php, src/Middlewares/RequestLogMiddleware.php, src/Middlewares/TracerMiddleware.php, src/Singletons/TracerSingleton.php, tests/Helpers/HttpHelperUnitTest.php, tests/Logs/RequestLogUnitTest.php, tests/Middlewares/TracerMiddlewareUnitTest.php, tests/Singletons/TracerSingletonUnitTest.php, tests/TestCase.php
- Desenvolvido Middleware para tracer.
- Desenvolvido testes unitários para o mesmo
- Alterado HttpHelper e RequestLogMiddleware para usar o Tracer.
- Documentado Tracer e RequestLogMiddleware.
=> TracerMiddleware

README.md, bootstrap/start.php, composer.lock, src/Functionalities/PropertiesAttacherFunctionality.php, src/Functionalities/ValuesExporterToJsonFunctionality.php, src/Helpers/HttpHelper.php, tests/Exceptions/ApiExceptionUnitTest.php, tests/Exceptions/BadImplementationExceptionUnitTest.php, tests/Exceptions/SecurityExceptionUnitTest.php, tests/Exceptions/UnavailableServiceExceptionUnitTest.php, tests/Functionalities/PropertiesAttacherFunctionalityUnitTest.php, tests/Functionalities/PropertiesExporterFunctionalityUnitTest.php, tests/Functionalities/ValuesExporterToArrayFunctionalityUnitTest.php, tests/Functionalities/ValuesExporterToJsonFunctionalityUnitTest.php, tests/Handlers/ExceptionHandlerUnitTest.php, tests/Helpers/EnumHelperUnitTest.php, tests/Helpers/HttpHelperUnitTest.php, tests/Helpers/TokenHelperUnitTest.php, tests/Logs/RequestLogUnitTest.php
- Criado ValuesExporterToJsonFunctionality.php
- Criado testes unitarios para nova classe.
- Corrigido alguns testes errados no projeto.
- Atualizado README.md
- Atualizado dependencias
- LOG-9541
=> (LOG-9541) - ValuesExporterToJsonFunctionality

README.md, src/Middlewares/AccreditedApiKeysMiddleware.php, tests/Middlewares/AccreditedApiKeysMiddlewareUnitTest.php
- Mudando de x-api-key para x-infra-key
- LOG-8941
=> (LOG-8941) - X-Api-Key turns in X-Infra-Key

README.md, src/Middlewares/AccreditedApiKeysMiddleware.php, tests/Middlewares/AccreditedApiKeysMiddlewareUnitTest.php
X-Api-Key turns in X-Infra-Key
=> Release v0.5.0

.github/PULL_REQUEST_TEMPLATE.md, src/Handlers/ExceptionHandler.php, src/Middlewares/RequestLogMiddleware.php, src/Singletons/TracerSingleton.php, tests/Singletons/TracerSingletonUnitTest.php
- ADicionado tracer ao Request info e Exception Handler
- LOG-10124
- LOG-10125
=> (LOG-10124) - Usando Tracer em todos os logs

README.md, bootstrap/start.php, composer.json, src/Dto/Dto.php, src/Dto/ResponseTimePayloadDto.php, src/Enumerators/ErrorEnum.php, src/Functionalities/PropertiesAttacherFunctionality.php, src/Functionalities/ValuesExporterToArrayFunctionality.php, src/Functionalities/ValuesExporterToJsonFunctionality.php, src/Helpers/HttpHelper.php, src/Middlewares/ResponseTimeLogMiddleware.php, src/Middlewares/TracerMiddleware.php, tests/Functionalities/ValuesExporterToArrayFunctionalityUnitTest.php, tests/Functionalities/ValuesExporterToJsonFunctionalityUnitTest.php, tests/Helpers/HttpHelperUnitTest.php, tests/Middlewares/ResponseTimeLogMiddlewareUnitTest.php, tests/Middlewares/TracerMiddlewareUnitTest.php
- Criação do middleware para medir o tempo de retorno
- [LOG-10499](https://logcomex.atlassian.net/browse/LOG-10499)
- [LOG-10500](https://logcomex.atlassian.net/browse/LOG-10500)
=> (LOG-10499) - Criação do middleware para medir o tempo de retorno

src/Dto/ResponseTimePayloadDto.php, src/Middlewares/ResponseTimeLogMiddleware.php
Correção no middleware de salvar tempo de resposta medio
=> Release v0.6.4

src/Middlewares/ResponseTimeLogMiddleware.php
- Removido tipo de retorno na ResponseTimeLogMiddleware->handle para compatibilidade.
- [LOG-12710](https://logcomex.atlassian.net/browse/LOG-12710)
- [LOG-11460](https://logcomex.atlassian.net/browse/LOG-11460)
=> Release v0.6.6

.travis.yml, Dockerfile, bootstrap/start.php, composer.json, composer.lock, docker-compose.yml, src/Handlers/ExceptionHandler.php, tests/Middlewares/ResponseTimeLogMiddlewareUnitTest.php
- Adicionado compatibilidade com PHP 8 e Lumen 8
- [LOG-16970](https://logcomex.atlassian.net/browse/LOG-16970)
- [LOG-15277](https://logcomex.atlassian.net/browse/LOG-15277)
- [LOG-15785](https://logcomex.atlassian.net/browse/LOG-15785)
=> (LOG-16970) Adicionado compatibilidade com PHP 8 e Lumen 8

.travis.yml, Dockerfile, bootstrap/start.php, composer.json, composer.lock, docker-compose.yml, src/Handlers/ExceptionHandler.php, tests/Middlewares/ResponseTimeLogMiddlewareUnitTest.php
=> Release v1.0.0

src/Helpers/HttpHelper.php, tests/Helpers/HttpHelperUnitTest.php
- Adicionado método shouldReturnHttpCodeWhenError
- Teste unitário
- LOG-XXXX
- LOG-XXXX
=> Custom http status

src/Helpers/HttpHelper.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> Transferido os testes tambem

Dockerfile, src/Helpers/HttpHelper.php, tests/Helpers/HttpHelperUnitTest.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> Release v0.10.2

src/Middlewares/CorsMiddleware.php, tests/Middlewares/CorsMiddlewareUnitTest.php
- Ajusta o metodo pra receber dois tipos diferente de parametro
- LOG-22058
- LOG-22099
=> (LOG-25072)  Ajuste no CORS Middleware

src/Middlewares/CorsMiddleware.php, tests/Middlewares/CorsMiddlewareUnitTest.php
- Ajusta o metodo pra receber dois tipos diferente de parametro
- LOG-22058
- LOG-22099
=> (LOG-25072) Ajuste no CORS Middleware

src/Helpers/HttpHelper.php, tests/Helpers/HttpHelperUnitTest.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> Melhorado log de requisição no httphelper

src/Helpers/HttpHelper.php, tests/Helpers/HttpHelperUnitTest.php
=> Release v0.11.1

src/Helpers/HttpHelper.php, tests/Helpers/HttpHelperUnitTest.php
- Alterado o Client do guzzle para manter sessão
- LOG-25082
- LOG-23305
- LOG-23306
=> (LOG-25082) Alteração no Client

src/Handlers/ExceptionHandler.php, tests/Handlers/ExceptionHandlerUnitTest.php, tests/Loggers/LogcomexLoggerUnitTest.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> Alterado o Handler para retornar o trace para o pessoal externo

src/Singletons/TracerSingleton.php
- Alterado o texto fixo para uma constante. Boas praticas.
- LOG-35230
- LOG-37341
=> (LOG-35230) - Tracer Propagation, Limited!

composer.json
- Atualizar versão do Guzzle compatível com PHP 8
***update necessário para instalar o pacote illuminate/mail + mandrill driver em projeto que utiliza PHP 8.
- [LOG-44089](https://logcomex.atlassian.net/browse/LOG-44089)
- [LOG-46274](https://logcomex.atlassian.net/browse/LOG-46274)
- Ajustes estruturais / ambiente
=> (LOG-46511) - Atualizar pacote MS-Core 1.x (PHP 8)

src/Helpers/HttpHelper.php, tests/Helpers/HttpHelperUnitTest.php, tests/TestCase.php
- alterado formato do tempo que é exibido o tempo de requisição
- [LOG-55667](https://logcomex.atlassian.net/browse/LOG-55667)
- [LOG-55901](https://logcomex.atlassian.net/browse/LOG-55901)
=> (LOG-55667) - Medir tempo de request para a fonte app importador

src/Handlers/ExceptionHandler.php, tests/Handlers/ExceptionHandlerUnitTest.php
- Adicionada verificação de existência do método render() em classes de exception personalizadas
- LOG-60402
- LOG-60404
=> (LOG-60402) - Adicionada verificação exceções personalizadas

src/Helpers/HttpHelper.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> add base uri logs

src/Helpers/HttpHelper.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> solve url logs

.docker/docker-compose.yml, .docker/php7.Dockerfile, .github/workflows/pr-unit-tests.yml, .gitignore, composer.json
- featureN
- LOG-XXXX
- LOG-XXXX
=> Adicionando estrutura para o lumen 8. e 9.x, como tambem para o php 7.4 e 8.1

.github/CODEOWNERS
=> - Adicionado code owner ao projeto

CHANGELOG.md
Adicionado arquivo de change log
=> 2.x Changelog

src/Singletons/TracerSingleton.php
- featureN
- LOG-XXXX
- LOG-XXXX
=> Merging 0.x in 2.x
